//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct UNNotificationAttributedMessageContext;

    unsafe impl ClassType for UNNotificationAttributedMessageContext {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for UNNotificationAttributedMessageContext {}

#[cfg(feature = "UNNotificationContent")]
unsafe impl UNNotificationContentProviding for UNNotificationAttributedMessageContext {}

extern_methods!(
    unsafe impl UNNotificationAttributedMessageContext {
        #[method_id(@__retain_semantics Other contextWithSendMessageIntent:attributedContent:)]
        pub unsafe fn contextWithSendMessageIntent_attributedContent(
            send_message_intent: &INSendMessageIntent,
            attributed_content: &NSAttributedString,
        ) -> Retained<Self>;

        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl UNNotificationAttributedMessageContext {
        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
