//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct CADisplayLink;

    unsafe impl ClassType for CADisplayLink {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for CADisplayLink {}

extern_methods!(
    unsafe impl CADisplayLink {
        #[method_id(@__retain_semantics Other displayLinkWithTarget:selector:)]
        pub unsafe fn display_link_with_target_selector(
            target: &AnyObject,
            sel: Sel,
        ) -> Retained<CADisplayLink>;

        #[method(addToRunLoop:forMode:)]
        pub unsafe fn add_to_run_loop_for_mode(&self, runloop: &NSRunLoop, mode: &NSRunLoopMode);

        #[method(removeFromRunLoop:forMode:)]
        pub unsafe fn remove_from_run_loop_for_mode(
            &self,
            runloop: &NSRunLoop,
            mode: &NSRunLoopMode,
        );

        #[method(invalidate)]
        pub unsafe fn invalidate(&self);

        #[method(timestamp)]
        pub unsafe fn timestamp(&self) -> CFTimeInterval;

        #[method(duration)]
        pub unsafe fn duration(&self) -> CFTimeInterval;

        #[method(targetTimestamp)]
        pub unsafe fn target_timestamp(&self) -> CFTimeInterval;

        #[method(isPaused)]
        pub unsafe fn is_paused(&self) -> bool;

        #[method(setPaused:)]
        pub unsafe fn set_paused(&self, paused: bool);

        #[deprecated = "preferredFramesPerSecond"]
        #[method(frameInterval)]
        pub unsafe fn frame_interval(&self) -> NSInteger;

        #[deprecated = "preferredFramesPerSecond"]
        #[method(setFrameInterval:)]
        pub unsafe fn set_frame_interval(&self, frame_interval: NSInteger);

        #[deprecated]
        #[method(preferredFramesPerSecond)]
        pub unsafe fn preferred_frames_per_second(&self) -> NSInteger;

        #[deprecated]
        #[method(setPreferredFramesPerSecond:)]
        pub unsafe fn set_preferred_frames_per_second(
            &self,
            preferred_frames_per_second: NSInteger,
        );

        #[cfg(feature = "CAFrameRateRange")]
        #[method(preferredFrameRateRange)]
        pub unsafe fn preferred_frame_rate_range(&self) -> CAFrameRateRange;

        #[cfg(feature = "CAFrameRateRange")]
        #[method(setPreferredFrameRateRange:)]
        pub unsafe fn set_preferred_frame_rate_range(
            &self,
            preferred_frame_rate_range: CAFrameRateRange,
        );
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl CADisplayLink {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
