//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;
#[cfg(feature = "objc2-metal")]
use objc2_metal::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct CAMetalDisplayLinkUpdate;

    unsafe impl ClassType for CAMetalDisplayLinkUpdate {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for CAMetalDisplayLinkUpdate {}

extern_methods!(
    unsafe impl CAMetalDisplayLinkUpdate {
        #[cfg(all(feature = "CAMetalLayer", feature = "objc2-metal"))]
        #[method_id(@__retain_semantics Other drawable)]
        pub unsafe fn drawable(&self) -> Retained<ProtocolObject<dyn CAMetalDrawable>>;

        #[method(targetTimestamp)]
        pub unsafe fn target_timestamp(&self) -> CFTimeInterval;

        #[method(targetPresentationTimestamp)]
        pub unsafe fn target_presentation_timestamp(&self) -> CFTimeInterval;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl CAMetalDisplayLinkUpdate {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_protocol!(
    pub unsafe trait CAMetalDisplayLinkDelegate {
        #[method(metalDisplayLink:needsUpdate:)]
        unsafe fn metal_display_link_needs_update(
            &self,
            link: &CAMetalDisplayLink,
            update: &CAMetalDisplayLinkUpdate,
        );
    }

    unsafe impl ProtocolType for dyn CAMetalDisplayLinkDelegate {}
);

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct CAMetalDisplayLink;

    unsafe impl ClassType for CAMetalDisplayLink {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for CAMetalDisplayLink {}

extern_methods!(
    unsafe impl CAMetalDisplayLink {
        #[cfg(all(feature = "CALayer", feature = "CAMetalLayer"))]
        #[method_id(@__retain_semantics Init initWithMetalLayer:)]
        pub unsafe fn init_with_metal_layer(
            this: Allocated<Self>,
            layer: &CAMetalLayer,
        ) -> Retained<Self>;

        #[method(addToRunLoop:forMode:)]
        pub unsafe fn add_to_run_loop_for_mode(&self, runloop: &NSRunLoop, mode: &NSRunLoopMode);

        #[method(removeFromRunLoop:forMode:)]
        pub unsafe fn remove_from_run_loop_for_mode(
            &self,
            runloop: &NSRunLoop,
            mode: &NSRunLoopMode,
        );

        #[method(invalidate)]
        pub unsafe fn invalidate(&self);

        #[method_id(@__retain_semantics Other delegate)]
        pub unsafe fn delegate(
            &self,
        ) -> Option<Retained<ProtocolObject<dyn CAMetalDisplayLinkDelegate>>>;

        #[method(setDelegate:)]
        pub unsafe fn set_delegate(
            &self,
            delegate: Option<&ProtocolObject<dyn CAMetalDisplayLinkDelegate>>,
        );

        #[method(preferredFrameLatency)]
        pub unsafe fn preferred_frame_latency(&self) -> c_float;

        #[method(setPreferredFrameLatency:)]
        pub unsafe fn set_preferred_frame_latency(&self, preferred_frame_latency: c_float);

        #[cfg(feature = "CAFrameRateRange")]
        #[method(preferredFrameRateRange)]
        pub unsafe fn preferred_frame_rate_range(&self) -> CAFrameRateRange;

        #[cfg(feature = "CAFrameRateRange")]
        #[method(setPreferredFrameRateRange:)]
        pub unsafe fn set_preferred_frame_rate_range(
            &self,
            preferred_frame_rate_range: CAFrameRateRange,
        );

        #[method(isPaused)]
        pub unsafe fn is_paused(&self) -> bool;

        #[method(setPaused:)]
        pub unsafe fn set_paused(&self, paused: bool);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl CAMetalDisplayLink {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
