//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

// NS_TYPED_ENUM
pub type CAMediaTimingFillMode = NSString;

extern_protocol!(
    pub unsafe trait CAMediaTiming {
        #[method(beginTime)]
        unsafe fn begin_time(&self) -> CFTimeInterval;

        #[method(setBeginTime:)]
        unsafe fn set_begin_time(&self, begin_time: CFTimeInterval);

        #[method(duration)]
        unsafe fn duration(&self) -> CFTimeInterval;

        #[method(setDuration:)]
        unsafe fn set_duration(&self, duration: CFTimeInterval);

        #[method(speed)]
        unsafe fn speed(&self) -> c_float;

        #[method(setSpeed:)]
        unsafe fn set_speed(&self, speed: c_float);

        #[method(timeOffset)]
        unsafe fn time_offset(&self) -> CFTimeInterval;

        #[method(setTimeOffset:)]
        unsafe fn set_time_offset(&self, time_offset: CFTimeInterval);

        #[method(repeatCount)]
        unsafe fn repeat_count(&self) -> c_float;

        #[method(setRepeatCount:)]
        unsafe fn set_repeat_count(&self, repeat_count: c_float);

        #[method(repeatDuration)]
        unsafe fn repeat_duration(&self) -> CFTimeInterval;

        #[method(setRepeatDuration:)]
        unsafe fn set_repeat_duration(&self, repeat_duration: CFTimeInterval);

        #[method(autoreverses)]
        unsafe fn autoreverses(&self) -> bool;

        #[method(setAutoreverses:)]
        unsafe fn set_autoreverses(&self, autoreverses: bool);

        #[method_id(@__retain_semantics Other fillMode)]
        unsafe fn fill_mode(&self) -> Retained<CAMediaTimingFillMode>;

        #[method(setFillMode:)]
        unsafe fn set_fill_mode(&self, fill_mode: &CAMediaTimingFillMode);
    }

    unsafe impl ProtocolType for dyn CAMediaTiming {}
);

extern "C" {
    pub static kCAFillModeForwards: &'static CAMediaTimingFillMode;
}

extern "C" {
    pub static kCAFillModeBackwards: &'static CAMediaTimingFillMode;
}

extern "C" {
    pub static kCAFillModeBoth: &'static CAMediaTimingFillMode;
}

extern "C" {
    pub static kCAFillModeRemoved: &'static CAMediaTimingFillMode;
}
