//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct CATransaction;

    unsafe impl ClassType for CATransaction {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSObjectProtocol for CATransaction {}

extern_methods!(
    unsafe impl CATransaction {
        #[method(begin)]
        pub fn begin();

        #[method(commit)]
        pub fn commit();

        #[method(flush)]
        pub fn flush();

        #[method(lock)]
        pub unsafe fn lock();

        #[method(unlock)]
        pub unsafe fn unlock();

        #[method(animationDuration)]
        pub fn animation_duration() -> CFTimeInterval;

        #[method(setAnimationDuration:)]
        pub fn set_animation_duration(dur: CFTimeInterval);

        #[cfg(feature = "CAMediaTimingFunction")]
        #[method_id(@__retain_semantics Other animationTimingFunction)]
        pub fn animation_timing_function() -> Option<Retained<CAMediaTimingFunction>>;

        #[cfg(feature = "CAMediaTimingFunction")]
        #[method(setAnimationTimingFunction:)]
        pub fn set_animation_timing_function(function: Option<&CAMediaTimingFunction>);

        #[method(disableActions)]
        pub fn disable_actions() -> bool;

        #[method(setDisableActions:)]
        pub fn set_disable_actions(flag: bool);

        #[cfg(feature = "block2")]
        #[method(completionBlock)]
        pub unsafe fn completion_block() -> *mut block2::Block<dyn Fn()>;

        #[cfg(feature = "block2")]
        #[method(setCompletionBlock:)]
        pub unsafe fn set_completion_block(block: Option<&block2::Block<dyn Fn()>>);

        #[method_id(@__retain_semantics Other valueForKey:)]
        pub unsafe fn value_for_key(key: &NSString) -> Option<Retained<AnyObject>>;

        #[method(setValue:forKey:)]
        pub unsafe fn set_value_for_key(an_object: Option<&AnyObject>, key: &NSString);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl CATransaction {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern "C" {
    pub static kCATransactionAnimationDuration: &'static NSString;
}

extern "C" {
    pub static kCATransactionDisableActions: &'static NSString;
}

extern "C" {
    pub static kCATransactionAnimationTimingFunction: &'static NSString;
}

extern "C" {
    pub static kCATransactionCompletionBlock: &'static NSString;
}
