//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

pub type NWEndpointArray = NSArray<nw_endpoint_t>;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    #[cfg(feature = "NEAppProxyFlow")]
    pub struct NEAppProxyUDPFlow;

    #[cfg(feature = "NEAppProxyFlow")]
    unsafe impl ClassType for NEAppProxyUDPFlow {
        #[inherits(NSObject)]
        type Super = NEAppProxyFlow;
        type Mutability = InteriorMutable;
    }
);

#[cfg(feature = "NEAppProxyFlow")]
unsafe impl NSObjectProtocol for NEAppProxyUDPFlow {}

extern_methods!(
    #[cfg(feature = "NEAppProxyFlow")]
    unsafe impl NEAppProxyUDPFlow {
        #[cfg(feature = "block2")]
        #[method(readDatagramsAndFlowEndpointsWithCompletionHandler:)]
        pub unsafe fn readDatagramsAndFlowEndpointsWithCompletionHandler(
            &self,
            completion_handler: &block2::Block<
                dyn Fn(*mut NSArray<NSData>, *mut NWEndpointArray, *mut NSError),
            >,
        );

        #[cfg(all(feature = "NWEndpoint", feature = "block2"))]
        #[deprecated]
        #[method(readDatagramsWithCompletionHandler:)]
        pub unsafe fn readDatagramsWithCompletionHandler(
            &self,
            completion_handler: &block2::Block<
                dyn Fn(*mut NSArray<NSData>, *mut NSArray<NWEndpoint>, *mut NSError),
            >,
        );

        #[cfg(feature = "block2")]
        #[method(writeDatagrams:sentByFlowEndpoints:completionHandler:)]
        pub unsafe fn writeDatagrams_sentByFlowEndpoints_completionHandler(
            &self,
            datagrams: &NSArray<NSData>,
            remote_endpoints: &NWEndpointArray,
            completion_handler: &block2::Block<dyn Fn(*mut NSError)>,
        );

        #[cfg(all(feature = "NWEndpoint", feature = "block2"))]
        #[deprecated]
        #[method(writeDatagrams:sentByEndpoints:completionHandler:)]
        pub unsafe fn writeDatagrams_sentByEndpoints_completionHandler(
            &self,
            datagrams: &NSArray<NSData>,
            remote_endpoints: &NSArray<NWEndpoint>,
            completion_handler: &block2::Block<dyn Fn(*mut NSError)>,
        );

        #[method_id(@__retain_semantics Other localFlowEndpoint)]
        pub unsafe fn localFlowEndpoint(&self) -> Option<Retained<nw_endpoint_t>>;

        #[cfg(feature = "NWEndpoint")]
        #[deprecated]
        #[method_id(@__retain_semantics Other localEndpoint)]
        pub unsafe fn localEndpoint(&self) -> Option<Retained<NWEndpoint>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    #[cfg(feature = "NEAppProxyFlow")]
    unsafe impl NEAppProxyUDPFlow {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);
