//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;

use crate::*;

#[cfg(feature = "block2")]
pub type MTLDrawablePresentedHandler =
    *mut block2::Block<dyn Fn(NonNull<ProtocolObject<dyn MTLDrawable>>)>;

extern_protocol!(
    pub unsafe trait MTLDrawable: NSObjectProtocol + IsRetainable {
        #[method(present)]
        fn present(&self);

        #[method(presentAtTime:)]
        unsafe fn present_at_time(&self, presentation_time: CFTimeInterval);

        #[method(presentAfterMinimumDuration:)]
        unsafe fn present_after_minimum_duration(&self, duration: CFTimeInterval);

        #[cfg(feature = "block2")]
        #[method(addPresentedHandler:)]
        unsafe fn add_presented_handler(&self, block: MTLDrawablePresentedHandler);

        #[method(presentedTime)]
        unsafe fn presented_time(&self) -> CFTimeInterval;

        #[method(drawableID)]
        fn drawable_id(&self) -> NSUInteger;
    }

    unsafe impl ProtocolType for dyn MTLDrawable {}
);
