//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::__framework_prelude::*;
use objc2_foundation::*;

use crate::*;

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MTLTextureType(pub NSUInteger);
impl MTLTextureType {
    pub const MTLTextureType1D: Self = Self(0);
    pub const MTLTextureType1DArray: Self = Self(1);
    pub const MTLTextureType2D: Self = Self(2);
    pub const MTLTextureType2DArray: Self = Self(3);
    pub const MTLTextureType2DMultisample: Self = Self(4);
    #[doc(alias = "MTLTextureTypeCube")]
    pub const Cube: Self = Self(5);
    #[doc(alias = "MTLTextureTypeCubeArray")]
    pub const CubeArray: Self = Self(6);
    pub const MTLTextureType3D: Self = Self(7);
    pub const MTLTextureType2DMultisampleArray: Self = Self(8);
    #[doc(alias = "MTLTextureTypeTextureBuffer")]
    pub const TextureBuffer: Self = Self(9);
}

unsafe impl Encode for MTLTextureType {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for MTLTextureType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MTLTextureSwizzle(pub u8);
impl MTLTextureSwizzle {
    #[doc(alias = "MTLTextureSwizzleZero")]
    pub const Zero: Self = Self(0);
    #[doc(alias = "MTLTextureSwizzleOne")]
    pub const One: Self = Self(1);
    #[doc(alias = "MTLTextureSwizzleRed")]
    pub const Red: Self = Self(2);
    #[doc(alias = "MTLTextureSwizzleGreen")]
    pub const Green: Self = Self(3);
    #[doc(alias = "MTLTextureSwizzleBlue")]
    pub const Blue: Self = Self(4);
    #[doc(alias = "MTLTextureSwizzleAlpha")]
    pub const Alpha: Self = Self(5);
}

unsafe impl Encode for MTLTextureSwizzle {
    const ENCODING: Encoding = u8::ENCODING;
}

unsafe impl RefEncode for MTLTextureSwizzle {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MTLTextureSwizzleChannels {
    pub red: MTLTextureSwizzle,
    pub green: MTLTextureSwizzle,
    pub blue: MTLTextureSwizzle,
    pub alpha: MTLTextureSwizzle,
}

unsafe impl Encode for MTLTextureSwizzleChannels {
    const ENCODING: Encoding = Encoding::Struct(
        "?",
        &[
            <MTLTextureSwizzle>::ENCODING,
            <MTLTextureSwizzle>::ENCODING,
            <MTLTextureSwizzle>::ENCODING,
            <MTLTextureSwizzle>::ENCODING,
        ],
    );
}

unsafe impl RefEncode for MTLTextureSwizzleChannels {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// TODO: pub fn MTLTextureSwizzleChannelsMake(r: MTLTextureSwizzle,g: MTLTextureSwizzle,b: MTLTextureSwizzle,a: MTLTextureSwizzle,) -> MTLTextureSwizzleChannels;

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct MTLSharedTextureHandle;

    unsafe impl ClassType for MTLSharedTextureHandle {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSCoding for MTLSharedTextureHandle {}

unsafe impl NSObjectProtocol for MTLSharedTextureHandle {}

unsafe impl NSSecureCoding for MTLSharedTextureHandle {}

extern_methods!(
    unsafe impl MTLSharedTextureHandle {
        #[cfg(feature = "MTLDevice")]
        #[method_id(@__retain_semantics Other device)]
        pub fn device(&self) -> Retained<ProtocolObject<dyn MTLDevice>>;

        #[method_id(@__retain_semantics Other label)]
        pub fn label(&self) -> Option<Retained<NSString>>;
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl MTLSharedTextureHandle {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

// NS_OPTIONS
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MTLTextureUsage(pub NSUInteger);
bitflags::bitflags! {
    impl MTLTextureUsage: NSUInteger {
        #[doc(alias = "MTLTextureUsageUnknown")]
        const Unknown = 0x0000;
        #[doc(alias = "MTLTextureUsageShaderRead")]
        const ShaderRead = 0x0001;
        #[doc(alias = "MTLTextureUsageShaderWrite")]
        const ShaderWrite = 0x0002;
        #[doc(alias = "MTLTextureUsageRenderTarget")]
        const RenderTarget = 0x0004;
        #[doc(alias = "MTLTextureUsagePixelFormatView")]
        const PixelFormatView = 0x0010;
        #[doc(alias = "MTLTextureUsageShaderAtomic")]
        const ShaderAtomic = 0x0020;
    }
}

unsafe impl Encode for MTLTextureUsage {
    const ENCODING: Encoding = NSUInteger::ENCODING;
}

unsafe impl RefEncode for MTLTextureUsage {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

// NS_ENUM
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MTLTextureCompressionType(pub NSInteger);
impl MTLTextureCompressionType {
    #[doc(alias = "MTLTextureCompressionTypeLossless")]
    pub const Lossless: Self = Self(0);
    #[doc(alias = "MTLTextureCompressionTypeLossy")]
    pub const Lossy: Self = Self(1);
}

unsafe impl Encode for MTLTextureCompressionType {
    const ENCODING: Encoding = NSInteger::ENCODING;
}

unsafe impl RefEncode for MTLTextureCompressionType {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

extern_class!(
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub struct MTLTextureDescriptor;

    unsafe impl ClassType for MTLTextureDescriptor {
        type Super = NSObject;
        type Mutability = InteriorMutable;
    }
);

unsafe impl NSCopying for MTLTextureDescriptor {}

unsafe impl NSObjectProtocol for MTLTextureDescriptor {}

extern_methods!(
    unsafe impl MTLTextureDescriptor {
        #[cfg(feature = "MTLPixelFormat")]
        #[method_id(@__retain_semantics Other texture2DDescriptorWithPixelFormat:width:height:mipmapped:)]
        pub unsafe fn texture2_d_descriptor_with_pixel_format_width_height_mipmapped(
            pixel_format: MTLPixelFormat,
            width: NSUInteger,
            height: NSUInteger,
            mipmapped: bool,
        ) -> Retained<MTLTextureDescriptor>;

        #[cfg(feature = "MTLPixelFormat")]
        #[method_id(@__retain_semantics Other textureCubeDescriptorWithPixelFormat:size:mipmapped:)]
        pub unsafe fn texture_cube_descriptor_with_pixel_format_size_mipmapped(
            pixel_format: MTLPixelFormat,
            size: NSUInteger,
            mipmapped: bool,
        ) -> Retained<MTLTextureDescriptor>;

        #[cfg(all(feature = "MTLPixelFormat", feature = "MTLResource"))]
        #[method_id(@__retain_semantics Other textureBufferDescriptorWithPixelFormat:width:resourceOptions:usage:)]
        pub unsafe fn texture_buffer_descriptor_with_pixel_format_width_resource_options_usage(
            pixel_format: MTLPixelFormat,
            width: NSUInteger,
            resource_options: MTLResourceOptions,
            usage: MTLTextureUsage,
        ) -> Retained<MTLTextureDescriptor>;

        #[method(textureType)]
        pub fn texture_type(&self) -> MTLTextureType;

        #[method(setTextureType:)]
        pub fn set_texture_type(&self, texture_type: MTLTextureType);

        #[cfg(feature = "MTLPixelFormat")]
        #[method(pixelFormat)]
        pub fn pixel_format(&self) -> MTLPixelFormat;

        #[cfg(feature = "MTLPixelFormat")]
        #[method(setPixelFormat:)]
        pub fn set_pixel_format(&self, pixel_format: MTLPixelFormat);

        #[method(width)]
        pub fn width(&self) -> NSUInteger;

        #[method(setWidth:)]
        pub unsafe fn set_width(&self, width: NSUInteger);

        #[method(height)]
        pub fn height(&self) -> NSUInteger;

        #[method(setHeight:)]
        pub unsafe fn set_height(&self, height: NSUInteger);

        #[method(depth)]
        pub fn depth(&self) -> NSUInteger;

        #[method(setDepth:)]
        pub unsafe fn set_depth(&self, depth: NSUInteger);

        #[method(mipmapLevelCount)]
        pub fn mipmap_level_count(&self) -> NSUInteger;

        #[method(setMipmapLevelCount:)]
        pub unsafe fn set_mipmap_level_count(&self, mipmap_level_count: NSUInteger);

        #[method(sampleCount)]
        pub fn sample_count(&self) -> NSUInteger;

        #[method(setSampleCount:)]
        pub unsafe fn set_sample_count(&self, sample_count: NSUInteger);

        #[method(arrayLength)]
        pub fn array_length(&self) -> NSUInteger;

        #[method(setArrayLength:)]
        pub unsafe fn set_array_length(&self, array_length: NSUInteger);

        #[cfg(feature = "MTLResource")]
        #[method(resourceOptions)]
        pub fn resource_options(&self) -> MTLResourceOptions;

        #[cfg(feature = "MTLResource")]
        #[method(setResourceOptions:)]
        pub fn set_resource_options(&self, resource_options: MTLResourceOptions);

        #[cfg(feature = "MTLResource")]
        #[method(cpuCacheMode)]
        pub fn cpu_cache_mode(&self) -> MTLCPUCacheMode;

        #[cfg(feature = "MTLResource")]
        #[method(setCpuCacheMode:)]
        pub fn set_cpu_cache_mode(&self, cpu_cache_mode: MTLCPUCacheMode);

        #[cfg(feature = "MTLResource")]
        #[method(storageMode)]
        pub fn storage_mode(&self) -> MTLStorageMode;

        #[cfg(feature = "MTLResource")]
        #[method(setStorageMode:)]
        pub fn set_storage_mode(&self, storage_mode: MTLStorageMode);

        #[cfg(feature = "MTLResource")]
        #[method(hazardTrackingMode)]
        pub fn hazard_tracking_mode(&self) -> MTLHazardTrackingMode;

        #[cfg(feature = "MTLResource")]
        #[method(setHazardTrackingMode:)]
        pub fn set_hazard_tracking_mode(&self, hazard_tracking_mode: MTLHazardTrackingMode);

        #[method(usage)]
        pub fn usage(&self) -> MTLTextureUsage;

        #[method(setUsage:)]
        pub fn set_usage(&self, usage: MTLTextureUsage);

        #[method(allowGPUOptimizedContents)]
        pub fn allow_gpu_optimized_contents(&self) -> bool;

        #[method(setAllowGPUOptimizedContents:)]
        pub fn set_allow_gpu_optimized_contents(&self, allow_gpu_optimized_contents: bool);

        #[method(compressionType)]
        pub unsafe fn compression_type(&self) -> MTLTextureCompressionType;

        #[method(setCompressionType:)]
        pub unsafe fn set_compression_type(&self, compression_type: MTLTextureCompressionType);

        #[method(swizzle)]
        pub fn swizzle(&self) -> MTLTextureSwizzleChannels;

        #[method(setSwizzle:)]
        pub fn set_swizzle(&self, swizzle: MTLTextureSwizzleChannels);
    }
);

extern_methods!(
    /// Methods declared on superclass `NSObject`
    unsafe impl MTLTextureDescriptor {
        #[method_id(@__retain_semantics Init init)]
        pub unsafe fn init(this: Allocated<Self>) -> Retained<Self>;

        #[method_id(@__retain_semantics New new)]
        pub unsafe fn new() -> Retained<Self>;
    }
);

extern_protocol!(
    #[cfg(feature = "MTLResource")]
    pub unsafe trait MTLTexture: MTLResource + IsRetainable {
        #[deprecated = "Use parentTexture or buffer instead"]
        #[method_id(@__retain_semantics Other rootResource)]
        fn root_resource(&self) -> Option<Retained<ProtocolObject<dyn MTLResource>>>;

        #[method_id(@__retain_semantics Other parentTexture)]
        fn parent_texture(&self) -> Option<Retained<ProtocolObject<dyn MTLTexture>>>;

        #[method(parentRelativeLevel)]
        fn parent_relative_level(&self) -> NSUInteger;

        #[method(parentRelativeSlice)]
        fn parent_relative_slice(&self) -> NSUInteger;

        #[cfg(feature = "MTLBuffer")]
        #[method_id(@__retain_semantics Other buffer)]
        fn buffer(&self) -> Option<Retained<ProtocolObject<dyn MTLBuffer>>>;

        #[method(bufferOffset)]
        fn buffer_offset(&self) -> NSUInteger;

        #[method(bufferBytesPerRow)]
        fn buffer_bytes_per_row(&self) -> NSUInteger;

        #[method(iosurfacePlane)]
        fn iosurface_plane(&self) -> NSUInteger;

        #[method(textureType)]
        fn texture_type(&self) -> MTLTextureType;

        #[cfg(feature = "MTLPixelFormat")]
        #[method(pixelFormat)]
        fn pixel_format(&self) -> MTLPixelFormat;

        #[method(width)]
        fn width(&self) -> NSUInteger;

        #[method(height)]
        fn height(&self) -> NSUInteger;

        #[method(depth)]
        fn depth(&self) -> NSUInteger;

        #[method(mipmapLevelCount)]
        fn mipmap_level_count(&self) -> NSUInteger;

        #[method(sampleCount)]
        fn sample_count(&self) -> NSUInteger;

        #[method(arrayLength)]
        fn array_length(&self) -> NSUInteger;

        #[method(usage)]
        fn usage(&self) -> MTLTextureUsage;

        #[method(isShareable)]
        fn is_shareable(&self) -> bool;

        #[method(isFramebufferOnly)]
        fn is_framebuffer_only(&self) -> bool;

        #[optional]
        #[method(firstMipmapInTail)]
        fn first_mipmap_in_tail(&self) -> NSUInteger;

        #[optional]
        #[method(tailSizeInBytes)]
        fn tail_size_in_bytes(&self) -> NSUInteger;

        #[optional]
        #[method(isSparse)]
        fn is_sparse(&self) -> bool;

        #[method(allowGPUOptimizedContents)]
        fn allow_gpu_optimized_contents(&self) -> bool;

        #[method(compressionType)]
        unsafe fn compression_type(&self) -> MTLTextureCompressionType;

        #[cfg(feature = "MTLTypes")]
        #[method(gpuResourceID)]
        unsafe fn gpu_resource_id(&self) -> MTLResourceID;

        #[cfg(feature = "MTLTypes")]
        #[method(getBytes:bytesPerRow:bytesPerImage:fromRegion:mipmapLevel:slice:)]
        unsafe fn get_bytes_bytes_per_row_bytes_per_image_from_region_mipmap_level_slice(
            &self,
            pixel_bytes: NonNull<c_void>,
            bytes_per_row: NSUInteger,
            bytes_per_image: NSUInteger,
            region: MTLRegion,
            level: NSUInteger,
            slice: NSUInteger,
        );

        #[cfg(feature = "MTLTypes")]
        #[method(replaceRegion:mipmapLevel:slice:withBytes:bytesPerRow:bytesPerImage:)]
        unsafe fn replace_region_mipmap_level_slice_with_bytes_bytes_per_row_bytes_per_image(
            &self,
            region: MTLRegion,
            level: NSUInteger,
            slice: NSUInteger,
            pixel_bytes: NonNull<c_void>,
            bytes_per_row: NSUInteger,
            bytes_per_image: NSUInteger,
        );

        #[cfg(feature = "MTLTypes")]
        #[method(getBytes:bytesPerRow:fromRegion:mipmapLevel:)]
        unsafe fn get_bytes_bytes_per_row_from_region_mipmap_level(
            &self,
            pixel_bytes: NonNull<c_void>,
            bytes_per_row: NSUInteger,
            region: MTLRegion,
            level: NSUInteger,
        );

        #[cfg(feature = "MTLTypes")]
        #[method(replaceRegion:mipmapLevel:withBytes:bytesPerRow:)]
        unsafe fn replace_region_mipmap_level_with_bytes_bytes_per_row(
            &self,
            region: MTLRegion,
            level: NSUInteger,
            pixel_bytes: NonNull<c_void>,
            bytes_per_row: NSUInteger,
        );

        #[cfg(feature = "MTLPixelFormat")]
        #[method_id(@__retain_semantics New newTextureViewWithPixelFormat:)]
        fn new_texture_view_with_pixel_format(
            &self,
            pixel_format: MTLPixelFormat,
        ) -> Option<Retained<ProtocolObject<dyn MTLTexture>>>;

        #[cfg(feature = "MTLPixelFormat")]
        #[method_id(@__retain_semantics New newTextureViewWithPixelFormat:textureType:levels:slices:)]
        unsafe fn new_texture_view_with_pixel_format_texture_type_levels_slices(
            &self,
            pixel_format: MTLPixelFormat,
            texture_type: MTLTextureType,
            level_range: NSRange,
            slice_range: NSRange,
        ) -> Option<Retained<ProtocolObject<dyn MTLTexture>>>;

        #[method_id(@__retain_semantics New newSharedTextureHandle)]
        fn new_shared_texture_handle(&self) -> Option<Retained<MTLSharedTextureHandle>>;

        #[method_id(@__retain_semantics Other remoteStorageTexture)]
        fn remote_storage_texture(&self) -> Option<Retained<ProtocolObject<dyn MTLTexture>>>;

        #[cfg(feature = "MTLDevice")]
        #[method_id(@__retain_semantics New newRemoteTextureViewForDevice:)]
        unsafe fn new_remote_texture_view_for_device(
            &self,
            device: &ProtocolObject<dyn MTLDevice>,
        ) -> Option<Retained<ProtocolObject<dyn MTLTexture>>>;

        #[method(swizzle)]
        fn swizzle(&self) -> MTLTextureSwizzleChannels;

        #[cfg(feature = "MTLPixelFormat")]
        #[method_id(@__retain_semantics New newTextureViewWithPixelFormat:textureType:levels:slices:swizzle:)]
        unsafe fn new_texture_view_with_pixel_format_texture_type_levels_slices_swizzle(
            &self,
            pixel_format: MTLPixelFormat,
            texture_type: MTLTextureType,
            level_range: NSRange,
            slice_range: NSRange,
            swizzle: MTLTextureSwizzleChannels,
        ) -> Option<Retained<ProtocolObject<dyn MTLTexture>>>;
    }

    #[cfg(feature = "MTLResource")]
    unsafe impl ProtocolType for dyn MTLTexture {}
);
